name: CI/CD Pipeline

on:
  push:
    branches:
      - 'beta'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Up Java and Gradle
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: "21"
          cache: gradle

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleStandardRelease --no-daemon

      - name: Sign APK Release
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/standard/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Signed APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: standard-release-signed-apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
